version: '3'

services:

  steam_db:
    container_name: "steam_db"
    image: "postgres"
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: steam_db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 5
      
  steam_rs:
    container_name: "steam-rs"
    image: "knowai/daq:beta"
    ports:
      - 5050:5050
    environment:
      APP_MODE: Production
      DB_NAME: steam_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: steam_db
      DB_PORT: 5432

    volumes:
      - ./init_config/config.yml:/app/config.yml

    depends_on:
      steam_rs_db:
        condition: service_healthy
    links:
      - steam_rs_db:steam_rs_db